### ISSUE TITLE
Symfony

### ISSUE THREAD

**Issue by stephanvierkant** [sitepoint-editors/design4#1]
Sorry for spamming this repo, but I tried many ways to get in contact with Sitepoint, but all tweets/mails are ignored. I don't have another way to get in contact with Sitepoint.

Can someone please look at https://github.com/sitepoint-editors/awesome-symfony/issues/110?

**Comment by jameshibbard** [comment]
Can you send me a mail at james.hibbard@sitepoint.com and I'll do my best to make your concern is passed on to the correct people.

**Comment by jameshibbard** [comment]
Can you send me a mail at javascript@sitepoint.com and I'll do my best to make your concern is passed on to the correct people.

**Comment by jameshibbard** [comment]
Sorry about that, I'll send you a mail.

**Edit**: Done. I wrote to the address you list on your GH profile.

**Comment by stephanvierkant** [comment]
Still no response...

**Comment by jameshibbard** [comment]
Sorry about that. I just checked with HQ and it would be possible to either make the repo private or, if you are interested, we could  transfer ownership to you.

**Comment by stephanvierkant** [comment]
Yes, I'm happy to take over the repo.

**Comment by jameshibbard** [comment]
I just tried transferring ownership and ran into a couple of problems:

- stephanvierkant/awesome-symfony already exists
- You can only transfer a repository from an organization to yourself at this time (which I guess means that I don't have the correct permissions)

Before I go track down who does have the correct permissions (which might take a while), would it maybe be an acceptable solution to add you to the repo as a collaborator instead? That way you can approve PRs, close issues etc and bring things up-to-date as you see fit.

**Comment by jameshibbard** [comment]
Just added you. Please let me know if you need anything else :)
